Repository googleapis/nodejs-web-risk, pull requests merged in 2019-05, with the labels that each got.

#1 feat: initial generation of library
  .eslintignore
  .eslintrc.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  .gitignore
  .jsdoc.js
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node11/common.cfg
  .kokoro/continuous/node11/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node11/common.cfg
  .kokoro/presubmit/node11/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/presubmit/windows/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .nycrc
  .prettierignore
  .prettierrc
  CODE_OF_CONDUCT.md
  codecov.yaml
  package-lock.json
  package.json
  protos/google/cloud/webrisk/v1beta1/webrisk.proto
  renovate.json
  src/v1beta1/doc/google/cloud/webrisk/v1beta1/doc_webrisk.js
  src/v1beta1/doc/google/protobuf/doc_timestamp.js
  src/v1beta1/index.js
  src/v1beta1/web_risk_service_v1_beta1_client.js
  src/v1beta1/web_risk_service_v1_beta1_client_config.json
  synth.metadata
Labels: cla: yes

#2 feat: write quickstart sample and generate READMEs
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node11/common.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node11/common.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/release/publish.cfg
  .repo-metadata.json
  README.md
  package-lock.json
  package.json
  samples/.eslintrc.yml
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/system-test/quickstart.test.js
  src/v1beta1/web_risk_service_v1_beta1_client.js
  src/v1beta1/web_risk_service_v1_beta1_client_config.json
  synth.metadata
  test/.eslintrc.yml
  test/gapic-v1beta1.js
Labels: cla: yes

#5 fix: DEADLINE_EXCEEDED is idempotent
  src/v1beta1/web_risk_service_v1_beta1_client_config.json
  synth.metadata
Labels: cla: yes

#6 docs: fix npm install instructions
  src/index.js
Labels: cla: yes

#7 chore: release 1.0.0
  CHANGELOG.md
Labels: autorelease: pending, cla: yes

#12 fix: update package name
  src/v1beta1/web_risk_service_v1_beta1_client.js
  synth.metadata
  test/gapic-v1beta1.js
Labels: cla: yes

#13 chore: release 1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#14 build: introduce release-please
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#15 build: upload docs to googleapis.dev
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#16 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1beta1/web_risk_service_v1_beta1_client.js
  synth.metadata
Labels: cla: yes

#18 build: switch to Node.js container, which has Python installed
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .repo-metadata.json
Labels: cla: yes

#19 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#22 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
