Repository googleapis/nodejs-web-risk, pull requests merged in 2020-06, with the labels that each got.

#163 fix: version rearrange
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  webpack.config.js
Labels: cla: yes

#167 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/web_risk_service_client.ts
  src/v1beta1/web_risk_service_v1_beta1_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#170 fix: handle fallback option properly
  .kokoro/populate-secrets.sh
  src/v1/web_risk_service_client.ts
  src/v1beta1/web_risk_service_v1_beta1_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#171 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 fix: add CreateSubmission to webrisk/v1 config
  src/v1/web_risk_service_client_config.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#173 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
