Repository googleapis/nodejs-web-risk, pull requests merged in 2020-07, with the labels that each got.

#174 build: use bazel build
  src/v1/web_risk_service_client.ts
  synth.metadata
  synth.py
  test/gapic_web_risk_service_v1.ts
Labels: automerge, cla: yes

#175 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#178 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#180 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#181 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#182 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#183 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#184 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#185 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#187 docs: add link to CHANGELOG in README
  .kokoro/release/docs-devsite.cfg
  README.md
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
